# Generated by Django 3.2.12 on 2022-02-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220217_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storytest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('TypeofTest', models.CharField(default='N/A', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_Letterstest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_SentenceTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_Storiestest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_Wordsstest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='a901596d-c740-4e1f-bf80-3e80fd24f73e', editable=False),
        ),
        migrations.DeleteModel(
            name='PretestRecords',
        ),
        migrations.AddField(
            model_name='storytest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
