# Generated by Django 3.2.12 on 2022-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220217_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=500)),
                ('TestType', models.CharField(max_length=50)),
                ('Answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='storytest',
            name='Numberof_MissingWords',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='13e698c5-c084-49f1-bff2-857cba0ad7d8', editable=False),
        ),
    ]
