# Generated by Django 3.2.12 on 2022-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20220218_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Answer2',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='questions',
            name='Answer3',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='questions',
            name='Answer4',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='684283dc-a4ce-4ff3-8c58-2e585ed88ca8', editable=False),
        ),
    ]
