# Generated by Django 3.2.12 on 2022-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220218_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=500)),
                ('Answer1', models.CharField(max_length=20)),
                ('Answer2', models.CharField(max_length=20)),
                ('Answer3', models.CharField(max_length=20)),
                ('RightAnswer', models.CharField(max_length=20)),
                ('TypeofQsn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='RightAnswer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='742d8f97-0120-4ada-8612-2314f5993cfb', editable=False),
        ),
    ]
