# Generated by Django 3.2.12 on 2022-02-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20220220_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='0566a6de-f6cd-44c2-9f16-3f4629078ddb', editable=False),
        ),
        migrations.CreateModel(
            name='IntelligenceTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linguistic', models.IntegerField()),
                ('Logical', models.IntegerField()),
                ('Musical', models.IntegerField()),
                ('Spatial', models.IntegerField()),
                ('Bodily', models.IntegerField()),
                ('Intra', models.IntegerField()),
                ('Inter', models.IntegerField()),
                ('TopScoreSection', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
