# Generated by Django 3.2.12 on 2022-02-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20220221_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_PostTest',
            new_name='is_PostTestSentences',
        ),
        migrations.AddField(
            model_name='account',
            name='is_PostTestStories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_PostTestWords',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_PostTestletters',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='a5e7e424-d71c-4214-ab10-0ba8696a4fe7', editable=False),
        ),
        migrations.CreateModel(
            name='PostTestLettersScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
