# Generated by Django 3.2.12 on 2022-02-23 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20220222_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTestStoryQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=500)),
                ('TestType', models.CharField(max_length=50)),
                ('Answer', models.CharField(max_length=200)),
                ('Answer2', models.CharField(default='N/A', max_length=200)),
                ('Answer3', models.CharField(default='N/A', max_length=200)),
                ('Answer4', models.CharField(default='N/A', max_length=200)),
                ('RightAnswer', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='be43c200-e274-4bd7-a39a-2c412e9e12e0', editable=False),
        ),
        migrations.CreateModel(
            name='PostWordTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('TypeofTest', models.CharField(default='N/A', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostStorytestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('Numberof_MissingWords', models.IntegerField(default=0)),
                ('TypeofTest', models.CharField(default='N/A', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
